// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.7
// source: api/calculator.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instructions  []*Instruction         `protobuf:"bytes,1,rep,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculationRequest) Reset() {
	*x = CalculationRequest{}
	mi := &file_api_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculationRequest) ProtoMessage() {}

func (x *CalculationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculationRequest.ProtoReflect.Descriptor instead.
func (*CalculationRequest) Descriptor() ([]byte, []int) {
	return file_api_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *CalculationRequest) GetInstructions() []*Instruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

type CalculationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PrintResult         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculationResponse) Reset() {
	*x = CalculationResponse{}
	mi := &file_api_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculationResponse) ProtoMessage() {}

func (x *CalculationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculationResponse.ProtoReflect.Descriptor instead.
func (*CalculationResponse) Descriptor() ([]byte, []int) {
	return file_api_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *CalculationResponse) GetItems() []*PrintResult {
	if x != nil {
		return x.Items
	}
	return nil
}

type Instruction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Op    string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	Var   string                 `protobuf:"bytes,3,opt,name=var,proto3" json:"var,omitempty"`
	// Types that are valid to be assigned to Left:
	//
	//	*Instruction_LeftNum
	//	*Instruction_LeftVar
	Left isInstruction_Left `protobuf_oneof:"left"`
	// Types that are valid to be assigned to Right:
	//
	//	*Instruction_RightNum
	//	*Instruction_RightVar
	Right         isInstruction_Right `protobuf_oneof:"right"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instruction) Reset() {
	*x = Instruction{}
	mi := &file_api_calculator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instruction) ProtoMessage() {}

func (x *Instruction) ProtoReflect() protoreflect.Message {
	mi := &file_api_calculator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instruction.ProtoReflect.Descriptor instead.
func (*Instruction) Descriptor() ([]byte, []int) {
	return file_api_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *Instruction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Instruction) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *Instruction) GetVar() string {
	if x != nil {
		return x.Var
	}
	return ""
}

func (x *Instruction) GetLeft() isInstruction_Left {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *Instruction) GetLeftNum() float64 {
	if x != nil {
		if x, ok := x.Left.(*Instruction_LeftNum); ok {
			return x.LeftNum
		}
	}
	return 0
}

func (x *Instruction) GetLeftVar() string {
	if x != nil {
		if x, ok := x.Left.(*Instruction_LeftVar); ok {
			return x.LeftVar
		}
	}
	return ""
}

func (x *Instruction) GetRight() isInstruction_Right {
	if x != nil {
		return x.Right
	}
	return nil
}

func (x *Instruction) GetRightNum() float64 {
	if x != nil {
		if x, ok := x.Right.(*Instruction_RightNum); ok {
			return x.RightNum
		}
	}
	return 0
}

func (x *Instruction) GetRightVar() string {
	if x != nil {
		if x, ok := x.Right.(*Instruction_RightVar); ok {
			return x.RightVar
		}
	}
	return ""
}

type isInstruction_Left interface {
	isInstruction_Left()
}

type Instruction_LeftNum struct {
	LeftNum float64 `protobuf:"fixed64,4,opt,name=left_num,json=leftNum,proto3,oneof"`
}

type Instruction_LeftVar struct {
	LeftVar string `protobuf:"bytes,5,opt,name=left_var,json=leftVar,proto3,oneof"`
}

func (*Instruction_LeftNum) isInstruction_Left() {}

func (*Instruction_LeftVar) isInstruction_Left() {}

type isInstruction_Right interface {
	isInstruction_Right()
}

type Instruction_RightNum struct {
	RightNum float64 `protobuf:"fixed64,6,opt,name=right_num,json=rightNum,proto3,oneof"`
}

type Instruction_RightVar struct {
	RightVar string `protobuf:"bytes,7,opt,name=right_var,json=rightVar,proto3,oneof"`
}

func (*Instruction_RightNum) isInstruction_Right() {}

func (*Instruction_RightVar) isInstruction_Right() {}

type PrintResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Var           string                 `protobuf:"bytes,1,opt,name=var,proto3" json:"var,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrintResult) Reset() {
	*x = PrintResult{}
	mi := &file_api_calculator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrintResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintResult) ProtoMessage() {}

func (x *PrintResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_calculator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintResult.ProtoReflect.Descriptor instead.
func (*PrintResult) Descriptor() ([]byte, []int) {
	return file_api_calculator_proto_rawDescGZIP(), []int{3}
}

func (x *PrintResult) GetVar() string {
	if x != nil {
		return x.Var
	}
	return ""
}

func (x *PrintResult) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_api_calculator_proto protoreflect.FileDescriptor

const file_api_calculator_proto_rawDesc = "" +
	"\n" +
	"\x14api/calculator.proto\x12\x03api\"J\n" +
	"\x12CalculationRequest\x124\n" +
	"\finstructions\x18\x01 \x03(\v2\x10.api.InstructionR\finstructions\"=\n" +
	"\x13CalculationResponse\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.api.PrintResultR\x05items\"\xcc\x01\n" +
	"\vInstruction\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x10\n" +
	"\x03var\x18\x03 \x01(\tR\x03var\x12\x1b\n" +
	"\bleft_num\x18\x04 \x01(\x01H\x00R\aleftNum\x12\x1b\n" +
	"\bleft_var\x18\x05 \x01(\tH\x00R\aleftVar\x12\x1d\n" +
	"\tright_num\x18\x06 \x01(\x01H\x01R\brightNum\x12\x1d\n" +
	"\tright_var\x18\a \x01(\tH\x01R\brightVarB\x06\n" +
	"\x04leftB\a\n" +
	"\x05right\"5\n" +
	"\vPrintResult\x12\x10\n" +
	"\x03var\x18\x01 \x01(\tR\x03var\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value2L\n" +
	"\n" +
	"Calculator\x12>\n" +
	"\tCalculate\x12\x17.api.CalculationRequest\x1a\x18.api.CalculationResponseB\x18Z\x16calculator-service/apib\x06proto3"

var (
	file_api_calculator_proto_rawDescOnce sync.Once
	file_api_calculator_proto_rawDescData []byte
)

func file_api_calculator_proto_rawDescGZIP() []byte {
	file_api_calculator_proto_rawDescOnce.Do(func() {
		file_api_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_calculator_proto_rawDesc), len(file_api_calculator_proto_rawDesc)))
	})
	return file_api_calculator_proto_rawDescData
}

var file_api_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_calculator_proto_goTypes = []any{
	(*CalculationRequest)(nil),  // 0: api.CalculationRequest
	(*CalculationResponse)(nil), // 1: api.CalculationResponse
	(*Instruction)(nil),         // 2: api.Instruction
	(*PrintResult)(nil),         // 3: api.PrintResult
}
var file_api_calculator_proto_depIdxs = []int32{
	2, // 0: api.CalculationRequest.instructions:type_name -> api.Instruction
	3, // 1: api.CalculationResponse.items:type_name -> api.PrintResult
	0, // 2: api.Calculator.Calculate:input_type -> api.CalculationRequest
	1, // 3: api.Calculator.Calculate:output_type -> api.CalculationResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_calculator_proto_init() }
func file_api_calculator_proto_init() {
	if File_api_calculator_proto != nil {
		return
	}
	file_api_calculator_proto_msgTypes[2].OneofWrappers = []any{
		(*Instruction_LeftNum)(nil),
		(*Instruction_LeftVar)(nil),
		(*Instruction_RightNum)(nil),
		(*Instruction_RightVar)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_calculator_proto_rawDesc), len(file_api_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_calculator_proto_goTypes,
		DependencyIndexes: file_api_calculator_proto_depIdxs,
		MessageInfos:      file_api_calculator_proto_msgTypes,
	}.Build()
	File_api_calculator_proto = out.File
	file_api_calculator_proto_goTypes = nil
	file_api_calculator_proto_depIdxs = nil
}
